mutation AddBaseItem(
	$id: ID!
	$name: String!
	$productTaxonomy: String!
	$ingredients: [IngredientInput!]
	$products: [ProductInput!]
	$recordId: Int!
) {
	addBaseItem(
		id: $id
		name: $name
		productTaxonomy: $productTaxonomy
		ingredients: $ingredients
		products: $products
		recordId: $recordId
	) {
		id
		name
		productTaxonomy
	}
}
