query GetBaseItems {
  getBaseItems {
    id
    name
    productTaxonomy
    isForRecipes
    mappedRecipeCount
    mappedProductCount
    recordId
  }
}


/*
* Terminal Commands
* execute this query against an Apollo-hosted server
*/
curl --request POST \
  -H 'Content-Type: application/json' \
  --data '{ "query":"query {baseItems {id name productTaxonomy}}" }' \
  'http://localhost:3000/graphql'
